/**
 * Created by liuyu on 2017/5/23.
 */

export const BIND_CABINET_GET_LIST = 'BIND_CABINET_GET_LIST';
export const BIND_CABINET_GET_LIST_SUCCESS = 'BIND_CABINET_GET_LIST_SUCCESS';
export const BIND_CABINET_GET_LIST_ERROR = 'BIND_CABINET_GET_LIST_ERROR';

export const DELIVER_GET_LIST = 'DELIVER_GET_LIST';
export const DELIVER_GET_LIST_SUCCESS = 'DELIVER_GET_LIST_SUCCESS';
export const DELIVER_GET_LIST_ERROR = 'DELIVER_GET_LIST_ERROR';
export const DELIVER_GET_CABINET_LIST = 'DELIVER_GET_CABINET_LIST';
export const DELIVER_GET_CABINET_LIST_SUCCESS = 'DELIVER_GET_CABINET_LIST_SUCCESS';
export const DELIVER_GET_CABINET_LIST_ERROR = 'DELIVER_GET_CABINET_LIST_ERROR';
export const DELIVER_SET_CAN_SCAN = 'DELIVER_SET_CAN_SCAN';

export const NEW_DELIVER_GET_CONFIG = 'NEW_DELIVER_GET_CONFIG';
export const NEW_DELIVER_GET_CONFIG_SUCCESS = 'NEW_DELIVER_GET_CONFIG_SUCCESS';
export const NEW_DELIVER_GET_CONFIG_ERROR = 'NEW_DELIVER_GET_CONFIG_ERROR';
export const NEW_DELIVER_SET_BOX_INDEX = 'NEW_DELIVER_SET_BOX_INDEX';
export const NEW_DELIVER_DONE_SET_ID = 'NEW_DELIVER_DONE_SET_ID';

export const PICK_GET_DELIVER_LIST = 'PICK_GET_DELIVER_LIST';
export const PICK_GET_DELIVER_LIST_SUCCESS = 'PICK_GET_DELIVER_LIST_SUCCESS';
export const PICK_GET_DELIVER_LIST_ERROR = 'PICK_GET_DELIVER_LIST_ERROR';
export const PICK_GET_STORE_LIST = 'PICK_GET_STORE_LIST';
export const PICK_GET_STORE_LIST_SUCCESS = 'PICK_GET_STORE_LIST_SUCCESS';
export const PICK_GET_STORE_LIST_ERROR = 'PICK_GET_STORE_LIST_ERROR';
export const PICK_SET_PAGE = 'PICK_SET_PAGE';

export const STORE_GET_LIST = 'STORE_GET_LIST';
export const STORE_GET_LIST_SUCCESS = 'STORE_GET_LIST_SUCCESS';
export const STORE_GET_LIST_ERROR = 'STORE_GET_LIST_ERROR';

export const NEWSTORE_GET_CONFIG = 'NEWSTORE_GET_CONFIG';
export const NEWSTORE_GET_CONFIG_SUCCESS = 'NEWSTORE_GET_CONFIG_SUCCESS';
export const NEWSTORE_GET_CONFIG_ERROR = 'NEWSTORE_GET_CONFIG_ERROR';
export const NEWSTORE_SET_CABINET = 'NEWSTORE_SET_CABINET';
export const NEWSTORE_SET_MOBILE = 'NEWSTORE_SET_MOBILE';
export const NEWSTORE_SET_BOX_INDEX = 'NEWSTORE_SET_BOX_INDEX';
export const NEWSTORE_SET_TIME_INDEX = 'NEWSTORE_SET_TIME_INDEX';
export const NEWSTORE_SET_INIT = 'NEWSTORE_SET_INIT';
export const NEWSTORE_GET_PRICE = 'NEWSTORE_GET_PRICE';
export const NEWSTORE_GET_PRICE_SUCCESS = 'NEWSTORE_GET_PRICE_SUCCESS';
export const NEWSTORE_GET_PRICE_ERROR = 'NEWSTORE_GET_PRICE_ERROR';

export const DELIVER_FROM_GET_LIST = 'DELIVER_FROM_GET_LIST';
export const DELIVER_FROM_GET_LIST_SUCCESS = 'DELIVER_FROM_GET_LIST_SUCCESS';
export const DELIVER_FROM_GET_LIST_ERROR = 'DELIVER_FROM_GET_LIST_ERROR';

export const DELIVER_SEARCH_LOAD = 'DELIVER_SEARCH_LOAD';
export const DELIVER_SEARCH_LOAD_SUCCESS = 'DELIVER_SEARCH_LOAD_SUCCESS';
export const DELIVER_SEARCH_LOAD_ERROR = 'DELIVER_SEARCH_LOAD_ERROR';

export const UPLOAD_CER_SET_APARTMENTID = 'UPLOAD_CER_SET_APARTMENTID';
export const UPLOAD_CER_SET_UNITID = 'UPLOAD_CER_SET_UNITID';

export const SELECT_APT_LOAD = 'SELECT_APT_LOAD';
export const SELECT_APT_LOAD_SUCCESS = 'SELECT_APT_SUCCESS';
export const SELECT_APT_LOAD_ERROR = 'SELECT_APT_ERROR';

export const SELECT_UNIT_LOAD = 'SELECT_UNIT_LOAD';
export const SELECT_UNIT_LOAD_SUCCESS = 'SELECT_UNIT_LOAD_SUCCESS';
export const SELECT_UNIT_LOAD_ERROR = 'SELECT_UNIT_LOAD_ERROR';

export const ZIPPORA_HOME_LOAD = 'ZIPPORA_HOME_LOAD';
export const ZIPPORA_HOME_LOAD_SUCCESS = 'ZIPPORA_HOME_LOAD_SUCCESS';
export const ZIPPORA_HOME_LOAD_ERROR = 'ZIPPORA_HOME_LOAD_ERROR';
export const ZIPPORA_HOME_GET_MEMBER = 'ZIPPORA_HOME_GET_MEMBER';
export const ZIPPORA_HOME_GET_MEMBER_ERROR = 'ZIPPORA_HOME_GET_MEMBER_ERROR';
export const ZIPPORA_HOME_GET_MEMBER_SUCCESS = 'ZIPPORA_HOME_GET_MEMBER_SUCCESS';
export const ZIPPORA_HOME_SET_CAN_SCAN = 'ZIPPORA_HOME_SET_CAN_SCAN';

export const ZIPPORA_LOG_LOAD = 'ZIPPORA_LOG_LOAD';
export const ZIPPORA_LOG_LOAD_SUCCESS = 'ZIPPORA_LOG_LOAD_SUCCESS';
export const ZIPPORA_LOG_LOAD_ERROR = 'ZIPPORA_LOG_LOAD_ERROR';

export const STATEMENT_LOAD = 'STATEMENT_LOAD';
export const STATEMENT_LOAD_SUCCESS = 'STATEMENT_LOAD_SUCCESS';
export const STATEMENT_LOAD_ERROR = 'STATEMENT_LOAD_ERROR';

export const WALLET_LOAD_CREDIT_CARD_SUCCESS = 'WALLET_LOAD_CREDIT_CARD_SUCCESS';
export const WALLET_LOAD_CREDIT_CARD = 'WALLET_LOAD_CREDIT_CARD';
export const WALLET_LOAD_CREDIT_CARD_ERROR = 'WALLET_LOAD_CREDIT_CARD_ERROR';
export const WALLET_CHANGE_DEFAULT = 'WALLET_CHANGE_DEFAULT';
export const WALLET_DELETE_CARD = 'WALLET_DELETE_CARD';

export const RECHARGE_GET_CONFIG = 'RECHARGE_GET_CONFIG';
export const RECHARGE_GET_CONFIG_ERROR = 'RECHARGE_GET_CONFIG_ERROR';
export const RECHARGE_GET_CONFIG_SUCCESS = 'RECHARGE_GET_CONFIG_SUCCESS';
export const RECHARGE_SELECT_INDEX = 'RECHARGE_SELECT_INDEX';
export const RECHARGE_SELECT_PAYWAY = 'RECHARGE_SELECT_PAYWAY';

export const MYPICKUP_LOAD = 'MYPICKUP_LOAD';
export const MYPICKUP_LOAD_ERROR = 'MYPICKUP_LOAD_ERROR';
export const MYPICKUP_LOAD_SUCCESS = 'MYPICKUP_LOAD_SUCCESS';

export const ZIPLOCKER_PROFILE_LOAD = 'ZIPLOCKER_PROFILE_LOAD';
export const ZIPLOCKER_PROFILE_LOAD_SUCCESS = 'ZIPLOCKER_PROFILE_LOAD_SUCCESS';
export const ZIPLOCKER_PROFILE_LOAD_ERROR = 'ZIPLOCKER_PROFILE_LOAD_ERROR';

export const TRANSACTION_DELIVER_LOAD = 'TRANSACTION_DELIVER_LOAD';
export const TRANSACTION_DELIVER_LOAD_SUCCESS = 'TRANSACTION_DELIVER_LOAD_SUCCESS';
export const TRANSACTION_DELIVER_LOAD_ERROR = 'TRANSACTION_DELIVER_LOAD_ERROR';

export const TRANSACTION_PICKUP_LOAD = 'TRANSACTION_PICKUP_LOAD';
export const TRANSACTION_PICKUP_LOAD_SUCCESS = 'TRANSACTION_PICKUP_LOAD_SUCCESS';
export const TRANSACTION_PICKUP_LOAD_ERROR = 'TRANSACTION_PICKUP_LOAD_ERROR';